name: Build Binder DockerHub Image

on: [push]  # runs whenever you push to GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repo files
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build & push Binder image
      - name: Build and push Binder image
        uses: machine-learning-apps/repo2docker-action@master
        with:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/c964-binder:latest
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          BINDER_CACHE: true